name = "DiffEqUncertainty"
uuid = "ef61062a-5684-51dc-bb67-a0fcdec5c97d"
authors = ["Chris Rackauckas <accounts@chrisrackauckas.com>"]
version = "1.8.0"

[deps]
DiffEqBase = "2b5f629d-d688-5b77-993f-72d75c75574e"
Distributions = "31c24e10-a181-5473-b8eb-7969acd0382f"
KernelDensity = "5ab0869b-81aa-558d-bb23-cbf5423bbe9b"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
Parameters = "d96e819e-fc66-5662-9728-84c9c7592b0a"
Quadrature = "67601950-bd08-11e9-3c89-fd23fb4432d2"
Random = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"
RecursiveArrayTools = "731186ca-8d62-57ce-b412-fbd966d074cd"
Reexport = "189a3867-3050-52da-a836-e630ba90ab69"
StaticArrays = "90137ffa-7385-5640-81b9-e52037218182"
Statistics = "10745b16-79ce-11e8-11f9-7d13ad32a3b2"
Zygote = "e88e6eb3-aa80-5325-afca-941959d7151f"

[compat]
DiffEqBase = "6"
Distributions = "0.18, 0.19, 0.20, 0.21, 0.22, 0.23, 0.24"
KernelDensity = "0.6"
Quadrature = "0.1, 1.0"
Reexport = "0.2, 1.0"
julia = "1"
