name = "DiffEqUncertainty"
uuid = "ef61062a-5684-51dc-bb67-a0fcdec5c97d"
authors = ["Chris Rackauckas <accounts@chrisrackauckas.com>"]
version = "1.3.0"

[deps]
DiffEqBase = "2b5f629d-d688-5b77-993f-72d75c75574e"
Distributions = "31c24e10-a181-5473-b8eb-7969acd0382f"
Quadrature = "67601950-bd08-11e9-3c89-fd23fb4432d2"
Statistics = "10745b16-79ce-11e8-11f9-7d13ad32a3b2"

[compat]
DiffEqBase = "6"
Distributions = "0.18, 0.19, 0.20, 0.21"
Quadrature = "0.1, 1.0"
julia = "1"

[extras]
Cubature = "667455a9-e2ce-5579-9412-b964f529a492"
DiffEqProblemLibrary = "a077e3f3-b75c-5d7f-a0c6-6bc4c8ec64a9"
OrdinaryDiffEq = "1dea7af3-3e70-54e6-95c3-0bf5283fa5ed"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["DiffEqProblemLibrary", "Test", "OrdinaryDiffEq", "Cubature"]
