name = "SciMLExpectations"
uuid = "afe9f18d-7609-4d0e-b7b7-af0cb72b8ea8"
authors = ["Chris Rackauckas <accounts@chrisrackauckas.com>"]
version = "2.0.0"

[deps]
DiffEqBase = "2b5f629d-d688-5b77-993f-72d75c75574e"
Distributions = "31c24e10-a181-5473-b8eb-7969acd0382f"
Integrals = "de52edbc-65ea-441a-8357-d3a637375a31"
KernelDensity = "5ab0869b-81aa-558d-bb23-cbf5423bbe9b"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
Parameters = "d96e819e-fc66-5662-9728-84c9c7592b0a"
Random = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"
RecursiveArrayTools = "731186ca-8d62-57ce-b412-fbd966d074cd"
Reexport = "189a3867-3050-52da-a836-e630ba90ab69"
StaticArrays = "90137ffa-7385-5640-81b9-e52037218182"
Statistics = "10745b16-79ce-11e8-11f9-7d13ad32a3b2"
Zygote = "e88e6eb3-aa80-5325-afca-941959d7151f"

[compat]
DiffEqBase = "6"
Distributions = "0.23, 0.24, 0.25"
Integrals = "3.1"
KernelDensity = "0.6"
RecursiveArrayTools = "2"
Reexport = "0.2, 1.0"
Zygote = "0.6"
Parameters = "0.12"
Reexport = "0.2, 1.0"
StaticArrays = "1"
julia = "1.6"
