[deps]
DiffEqGPU = "071ae1c0-96b5-11e9-1965-c90190d839ea"
DiffEqNoiseProcess = "77a26b50-5914-5dd7-bc55-306e6241c503"
DifferentialEquations = "0c46a032-eb83-5123-abaf-570d42b7fbaa"
Distributions = "31c24e10-a181-5473-b8eb-7969acd0382f"
Documenter = "e30172f5-a6a5-5a46-863b-614d45cd2de4"
ForwardDiff = "f6369f11-7733-5829-9624-2563aa707210"
IntegralsCuba = "e00cd5f1-6337-4131-8b37-28b2fe4cd6cb"
KernelDensity = "5ab0869b-81aa-558d-bb23-cbf5423bbe9b"
MCMCChains = "c7f686f2-ff18-58e9-bc7b-31028e88f75d"
Optimization = "7f7a1694-90dd-40f0-9382-eb1efda571ba"
OptimizationMOI = "fd9f6733-72f4-499f-8506-86b2bdd0dea1"
OptimizationNLopt = "4e6fcdb7-1186-4e1f-a706-475e75c168bb"
OrdinaryDiffEq = "1dea7af3-3e70-54e6-95c3-0bf5283fa5ed"
Plots = "91a5bcdd-55d7-5caf-9e0b-520d859cae80"
SciMLExpectations = "afe9f18d-7609-4d0e-b7b7-af0cb72b8ea8"
SciMLSensitivity = "1ed8b502-d754-442c-8d5d-10ac956f44a1"
StatsPlots = "f3b207a7-027a-5e70-b257-86293d7955fd"
StochasticDiffEq = "789caeaf-c7a9-5a7d-9973-96adeb23e2a0"
Turing = "fce5fe82-541a-59a6-adf8-730c64b5f9a0"

[compat]
DiffEqGPU = "2, 3"
DiffEqNoiseProcess = "5"
DifferentialEquations = "7"
Distributions = "0.25"
Documenter = "1"
ForwardDiff = "0.10"
IntegralsCuba = "0.3"
KernelDensity = "0.6"
MCMCChains = "6"
Optimization = "3"
OptimizationMOI = "0.1"
OptimizationNLopt = "0.1, 0.2"
OrdinaryDiffEq = "6"
Plots = "1"
SciMLSensitivity = "7"
StatsPlots = "0.15"
StochasticDiffEq = "6"
Turing = "0.29"
